### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by akshay-sh6** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#127]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#3

**In which task and step of the codelab can this issue be found?**
In first illustration of function with parameters itself.

**Describe the problem**
The illustration of the function include return type while declaring the function but doesn't include the return statement

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot_20221215-093814](https://user-images.githubusercontent.com/104648563/207770422-d808c43e-4f22-4b87-87a1-f99a79c45c96.png)

**Comment by android-dev-lxl** [comment]
Hi @akshay-sh6 
Thank you for reaching out to us!

In [3. Return a value from function](https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#2), in the diagram, we explicitly mentioned the return statement since we discussed the return type and value. 
<img width="732" alt="image" src="https://user-images.githubusercontent.com/24260141/212207272-e557e4e2-c80a-47fc-8894-09f5abdedadb.png">


In [4. Add a parameter to the birthdayGreeting() function](https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#3), the focus is more on parameters. We skipped the return statement because it is part of the function body. 

<img width="726" alt="image" src="https://user-images.githubusercontent.com/24260141/212208234-331ad94c-ce22-457f-9124-33db6d43014c.png">

Hope this helps!

**Comment by osuleymanova** [comment]
Hello @akshay-sh6 ,

Closing this issue, since there is no response. 
Hope the issue was resolved thanks to the clarification given in the comment above. 
Please create a new one, if you still need any help.
