### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by ghost** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#230]
**_Build a basic layout activity_** in **_Android Basics with Compose_** requires urgent attention.

Some of the code-along videos don't match the actual codelabs.

When I am completing the codelab, the code I enter might receive an error message even though I am following the codelab correctly and also I receive errors even though an import package has been added.

Some of the code-along videos need to be updated to match exactly what's in the codelab.

The codelab content needs to be updated.

I spend several hours completing the codelab because they don't actually work. Then when I arrive at the practice codelab, I am slightly unsure what to do.

The codelabs need urgent attention.

**Comment by osuleymanova** [comment]
Hello @AndrewRowley,

Thank you for contacting us and sharing your feedback. We would really appreciate it if you let us know what exactly is not working. Please provide the codelab URL, section so that we can fix these issues.

**Comment by AndrewRowley** [comment]
Hi @osuleymanova,

Thank you for getting back.

I can't share precise detail as I would be here for over an hour doing this. Although, in **Android Basics with Compose** in **Build a Basic Layout,** in the codelabs **Build a simple app with text composables** and **Add images to your Android app** the code-along videos does not match the codelab and the videos are messy and not suitable to follow along. Also, in each codelab, the code-along videos don't match what's in the codelab.
Also, when I read through the codelab and write code in Android Studio, even though I have followed the codelab correctly, I still receive error messages in Android Studio.

Both ***Build a Basic Layout,** and **Build a simple app with text composables** ** need reviewing. 

I have completed both codelabs twice and I still don't know how to complete the **Practice: Compose Basics** because I am unable to complete the course due to it being messy and not working.

Although, with **Create your first Android app** codelab, I completed this with ease and was easy to follow along and the code-along video matched the the codelab.

I would like to re-do both *Build a Basic Layout,** and **Build a simple app with text composables** ** again Monday.

**Comment by osuleymanova** [comment]
Hello @AndrewRowley,

My apologies for the late reply. Currently we are working on the course maintenance, so the fix will be expected soon. I will keep you updated.

**Comment by AndyR23** [comment]
Thank you @osuleymanova :)

**Comment by android-dev-lxl** [comment]
@ghost
Could you please give us your specific issue and the version of the Android Studio you are using.

**Comment by johnshea** [comment]
NOTE - As the student did not reply and since we are making course updates and corrections, I will be closing this issue.
