### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by srikanth104** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#393]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#2)**

**Step 3 **

**The compose function that returns nothing and bears the @Composable annotation MUST be named using pascal case. Pascal case refers to a naming convention in which the first letter of each word in a compound word is capitalized. The difference between pascal case and camel case is that all words in pascal case are capitalized. In camel case, the first word is not capitalized. 

I have given camel case but still worked.  As per documentation composable function MUST be names as pascal. 

**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version: Android Studio Flamingo_ 
_API version of the emulator: _ 

**Additional information**
_
<img width="1344" alt="Screenshot 2023-07-22 at 10 40 12 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/16039757/be068c8a-a9d0-4184-a36c-74d065e94350">_

**Comment by johnshea** [comment]
Hi @srikanth104 

Thank you for writing in with your question.

These instructions are referring to the [API Guidelines for Jetpack Compose](https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-api-guidelines.md#api-guidelines-for-jetpack-compose) which are the guidelines to follow for best practices.

The "MUST" in this context refers to what the guidelines require in order to adhere to them. It is a coding convention and not a requirement of Jetpack Compose nor Android Studio.

Android Studio does not enforce this as you have seen.

Hope you are enjoying the course!

Regards.
