### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Silvrbckw** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#584]
**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to Screenshot in link below. Where the example is of an Android phone and YouTube video reviews. 
2. Should Number of Reviews be written in Kotlin Playground as a "Int" data type? Or a "Double" data type? I believe it should read "Double". Because Int is for whole numbers.
3. 
![Screenshot 2024-01-22 11 17 14 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/121541003/77c39f74-23e3-4cce-b8ab-1a98b402b75a)

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Silvrbckw 

Thank you for writing in with your question.

Technically "Int" is the correct data type since it is not counting partial views. Views is a whole number but I believe the confusion is caused by the formatting of the number which shows it with a decimal.

I will share this with the team in case they wish to rework this example based on your feedback.

Hope you are enjoying the course.

Regards.

**Comment by Silvrbckw** [comment]
Thanks for your prompt response @johnshea . I agree with you. Based on what I was learning it confused me to see the decimal.

**Comment by Silvrbckw** [comment]
Commit
