### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by Sachin-M-at-git** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#597]
**URL of codelab :**

https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#8

**In which task and step of the codelab can this issue be found?**

The problem is on line number 48 `modifier = modifier`

**Describe the problem**
The column doesn't align itself in the center vertically as depicted in the goal image of the codelab.
I solved it by fitting the column to max height of the screen by altering the code on line number 48 as follows:
`modifier = modifier.fillMaxHeight()`

**Comment by johnshea** [comment]
Hi @Sachin-M-at-git 

Thank you for writing in with your issue.

Please provide screenshots of all of your original code, the code running on an emulator, and what the issue is so we can try to duplicate it and troubleshoot it further.

It was not clear from your description.

Looking forward to your response.

Regards.

**Comment by johnshea** [comment]
Hi @Sachin-M-at-git 

As we have not received a follow up from you, the issue will be closed at this time.

If you are still experiencing the problem, please create a new issue and provide the requested information.

Regards.
