### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by JoshDrentlaw** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#599]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#3

**In which task and step of the codelab can this issue be found?**
Task 4: "Add Box Layout", Step 5 (but labeled step 3)

**Describe the problem**
One mistake is that step 5 is labeled step 3.
The main mistake I want to report is in the final code for the `GreetingImage()` method, the modifier being passed into `GreetingText()` method has `.fillMaxSize()` chained on it. Leaving the `.fillMaxSize()` method throws off the layout, and it should instead be added to the `Column` modifier in the `GreetingText()` method.

**Steps to reproduce?**
1. Follow code lab up to Task 4
2. Finish adding the `Image` and the `Box`
3. The `.fillMaxSize()` being passed into `GreetingText()` will make every element in that method (`Column` and 2 `Text`s) fill the max size which throws off the layout and stops all the text from being vertically centered.
4. Remove the original `.fillMaxSize()` and add it to the `Column`'s modifier and the layout returns to normal.

**Versions**
_Android Studio version:_ Hedgehog 2023.1.1 Patch 1
_API version of the emulator:_ 34 extension level 7

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
With `.fillMaxSize()` in the wrong place
<img width="804" alt="Screenshot 2024-02-11 at 8 45 31 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/13529723/a23e3129-8d31-4b32-9621-97672b1cefc9">

With `.fillMaxSize()` in the correct place
<img width="804" alt="Screenshot 2024-02-11 at 8 46 07 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/13529723/a9cfc597-6a05-49e3-b475-5b3b3dc1dbfd">

**Comment by johnshea** [comment]
Hi @JoshDrentlaw 

Thank you for writing in with your issue.

First, you are correct that the steps are mis-numbered. Thank you for pointing that out and it will be corrected.

As for the layout issue, that is caused by a difference in your code.

For the `from` Text composable, it should be `modifier = Modifier` but your code has `modifier = modifier`. By using `modifier` it is using the argument passed in which already has `.fillMaxSize()` which is throwing off your layout.  Please correct and see if you are still having an issue.

Your code with the lowercase "m"...
<img width="881" alt="Screenshot 2024-03-20 at 9 40 45 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/7107817/e34ad4a3-cf1e-4ce9-af4b-5953b7927811">

What the previous codelab instructed...
<img width="1467" alt="Screenshot 2024-03-20 at 9 42 11 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/7107817/231029b9-d48e-474c-96b3-c7f34387dee6">

Hope you are enjoying the course!

Regards.
