### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by DracoVenturus** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#655]
**URL of codelab**
[Codelab link](https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app)

**In which task and step of the codelab can this issue be found?**
Create your first Android app, steps 4 and 7

**Describe the problem**
The name does not update in the preview when I do as requested in steps 4 and 7, I.E. updating it in `fun GreetingPreview`; it only does if I update it in `fun onCreate`

**Steps to reproduce?**
1. Do as described in step 4 or in step 7's Code snippet for review
2. Update the preview
3. The name remains the one in `fun onCreate`

**Versions**
_Android Studio version:_ Iguana | 2023.2.1 Patch 2
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/42717091/73624497-db6b-4274-b6e5-6275fc822fcb)

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/42717091/371352f9-f6dc-4fa4-b158-567b726cebcf)

**Comment by DracoVenturus** [comment]
Sorry, the correct link is just [This one](https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app)

**Comment by johnshea** [comment]
Hi @DracoVenturus 

Thank you for writing in.

From you screenshots, you are only viewing the emulator. You are not viewing the preview which is why you are not seeing it.

You need to click either "Split" or "Design" as indicated in the following image.

<img width="856" alt="Screenshot 2024-04-16 at 11 34 08 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/7107817/3a8b0f9e-01ff-4da8-8d7a-2cf96aabb003">

Hope you are enjoying the course!

Regards.

**Comment by DracoVenturus** [comment]
You are so very right @johnshea I was seeing what I wanted to see instead of what I actually had to :-)
Yes I like the course, I will be a very slow learner, but a learner nonetheless!
