### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by ehsung2019** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#661]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#3

**In which task and step of the codelab can this issue be found?**
Update the GreetingPreview() function with your name. Then rebuild and check out your personalized greeting card!

**Describe the problem**
the name was changed when i update Greeting("Android") from setContent {} instead of GreetingPreview() 

**Steps to reproduce?**
1. Go to...Greeting("Android") 
2. Click on..."Android"
3. See error...no change

**Versions**
_Android Studio version:_ Android Studio Koala | 2024.1.1 Canary 5
Build #AI-241.14494.240.2411.11700778, built on April 11, 2024
Runtime version: 17.0.10+0--11679475 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  ide.experimental.ui=true

_API version of the emulator:_ used physical device (lge lm-v600)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Westodd** [comment]
Hello,

Take this with a grain of salt because I'm leaning Kotlin just like you. I'm not sure if there's a bug, although I understand your reasoning. However, in the exercise, you're not asked to run the application, but rather to recreate a preview, which, to me, are two distinct things ! 🙂

Have a look below:

![preview](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/167121858/4aa5ac78-ec18-423f-b000-de0c223b6660)

I hope it will help you !

**Comment by johnshea** [comment]
Hi @ehsung2019 

As @Westodd noted, if you rebuild the app and run on an emulator it will show the updated name since you changed it.

If you check the preview, it will still have the existing name as you did not change it.

Hope you are enjoying the course.

Regards.
