### ISSUE TITLE
Text composables: Android Basics with Compose: end codelab button missing

### ISSUE THREAD

**Issue by RobbeVO** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#664]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables#10)

step 11

there is no button to end the codelab or link to the next one only to more information about the current codelab

**Steps to reproduce?**
1. Go to Unit One Codelab birthday card text composables
2. Search for button or link to progress
3. See nothing but links to more information about the current codelab

**Versions**
_Android Studio version: N.A.
_API version of the emulator: N.A.

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/153361978/aa929983-0d42-4ed7-a313-d2cf099e96f5)

**Comment by johnshea** [comment]
Hi @RobbeVO 

Thank you for writing in.

This is because you are navigating directly to the codelab and not going thru the Android Basic with Compose course link.

Please go to this through https://developer.android.com/courses/android-basics-compose/course and you should be good.

Hope you are enjoying the course!

Regards.
