### ISSUE TITLE
Connect your Android device: Android Basics with Compose

### ISSUE THREAD

**Issue by koljae** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#68]
**URL of codelab**
1) https://developer.android.com/codelabs/basic-android-kotlin-compose-emulator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-emulator#2

2) https://developer.android.com/codelabs/basic-android-kotlin-compose-connect-device?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-connect-device#4

**In which task and step of the codelab can this issue be found?**
1) "Run your app on the Android Emulator"
2) 5 - Click run and you can deploy your app to your device.

**Describe the problem**
The "Design" preview in Android Studio correctly displays the substituted name, in my case "Kolja".
The emulator displays the default name "Android" instead. 
The same is true when I test it on my device which is a Pixel 6 Pro with Android version 13 installed.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 2021.3.1 Dolphin
_API version of the emulator:_ Pixel 6 Pro API 31

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

Code:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/4474090/192116417-7d99daa5-1025-46d7-98f1-cdeaa2e33149.png">

Design Preview
<img width="368" alt="image" src="https://user-images.githubusercontent.com/4474090/192116442-4704fb41-6a67-4ce9-a9d5-72bae71e344a.png">

Emulator
<img width="275" alt="image" src="https://user-images.githubusercontent.com/4474090/192116460-522eebe9-49b8-4564-aa8f-2b217eca4722.png">

Pixel 6
![image](https://user-images.githubusercontent.com/4474090/192117182-70650aa1-09b8-4697-bd81-53fb9e9415ae.png)

**Comment by johnshea** [comment]
Hi @koljae.

From the code you pasted and your description, I can see that you are changing the name in the `@Preview` composable which is why you see it in the *Design* pane but you did not change it in the `onCreate()` function which is what runs on the device/emulator. If you look, it still shows "Android".

Please review step "[5. Update the text](https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app)" as this teaches what you need to change to get this to work as expected.

If you are still having a problem, please do not hesitate to open another issue.

Hope you are enjoying the course!

Regards.
