### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by Aldrich-Robert-Mark** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#81]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#4

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
What is presented in the codelab does not match what Android Studio has presented to me.
codelab:
![image](https://user-images.githubusercontent.com/19937279/194806056-cf6540a5-9bcb-4d1b-9c0b-4418c81009c3.png)
Android Studio:
![image](https://user-images.githubusercontent.com/19937279/194806145-354e9eed-c3ac-49d2-91cf-9060c82c76c1.png)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
![image](https://user-images.githubusercontent.com/19937279/194806291-0ccc5f34-763e-4145-933e-570407df65df.png)

_API version of the emulator:_ 
![image](https://user-images.githubusercontent.com/19937279/194806357-3921c9da-d9ad-4110-8f85-4b6b8fa870dd.png)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Aldrich-Robert-Mark 
Thank you for contacting us. 
The screenshot provided shows that you created the project using the template Empty Activity rather than Empty Compose Activity:

![Screen Shot 2022-10-13 at 11 34 56 AM](https://user-images.githubusercontent.com/86437155/195679434-14342031-da3b-43c9-b710-53eabf50b65c.png)

You need to follow the steps to create a new project using the template "Empty Compose Activity" as described in the codelab, so the code snippets from the codelab will be the same as the code in Android Studio project.
